# ==========================================
# APPLICATION
# ==========================================
spring.application.name=customerapi-service
server.port=7003

# ==========================================
# H2 IN-MEMORY DATABASE
# ==========================================
spring.datasource.url=jdbc:h2:mem:customer_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# H2 CONSOLE
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# EUREKA CLIENT
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-service-67d7.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always